# Model Training

### 1.1 Import Data and Required Packages
#### Importing Pandas, Numpy, Matplotlib, Seaborn and Warings Library.

In [2]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

#### Import the CSV Data as Pandas DataFrame

In [10]:
df = pd.read_csv('data/stud1.csv')

#### Show Top 5 Records

In [11]:
df.head()

,Unnamed: 0,gender,race_ethnicity,parent_education,lunch_type,test_prep_course,math_score,reading_score,writing_score,total_score,average
0,0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,4,male,group C,some college,standard,none,76,78,75,229,76.333333

#### Preparing X and Y variables

In [21]:
X = df.drop(columns=['math_score', "Unnamed: 0", "total_score", "average"])
X.head()

,gender,race_ethnicity,parent_education,lunch_type,test_prep_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [22]:
print("Categories in 'gender' variable:     ",end=" ")
print(df['gender'].unique().tolist())

print("Categories in 'race_ethnicity' variable:  ",end=" ")
print(df['race_ethnicity'].unique().tolist())

print("Categories in'parent_education' variable:",end=" " )
print(df['parent_education'].unique().tolist())

print("Categories in 'lunch_type' variable:     ",end=" " )
print(df['lunch_type'].unique().tolist())

print("Categories in 'test_prep_course' variable:     ",end=" " )
print(df['test_prep_course'].unique().tolist())

Categories in 'gender' variable:      ['female', 'male']
Categories in 'race_ethnicity' variable:   ['group B', 'group C', 'group A', 'group D', 'group E']
Categories in'parent_education' variable: ["bachelor's degree", 'some college', "master's degree", "associate's degree", 'high school', 'some high school']
Categories in 'lunch_type' variable:      ['standard', 'free/reduced']
Categories in 'test_prep_course' variable:      ['none', 'completed']

In [23]:
# y = df['math_score']
# y

In [24]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features),
    ]
)

C:\Users\DELL\AppData\Local\Temp\ipykernel_5744\3049432719.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = X.select_dtypes(include="object").columns

In [25]:
X = preprocessor.fit_transform(X)

In [26]:
X.shape

(1000, 19)

In [28]:
# separate data into train and test 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((800, 19), (200, 19))

#### Create an Evaluate Function to give all metrics after model Training

In [ ]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_score = r2_score(true, predicted)
    return mae, mse, rmse, r2_score